spring.datasource.url=jdbc:mysql://production-server:3306/timetable_management
spring.datasource.username=prod_user
spring.datasource.password=prod_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false